version: '2'
services:

  # webserver
  eric_webserver:
    image: nginx
    container_name: eric_webserver
    ports:
      - "80:80"
    links:
      - eric_app
    volumes:
      - "./www:/var/www"
      - "./.docker/config/nginx/vhost/sf4_vhost:/etc/nginx/conf.d/030-sf4.conf:ro"

  # main app
  eric_app:
    build: .docker
    container_name: eric_app
    links:
      - eric_database
    volumes:
      - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
      - "./www:/var/www"
    ports:
      - "9000:9000"

    working_dir: "/var/www"

  # database
  eric_database:
    image: mysql
    container_name: eric_database
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

